version: '3'

services:
  web:
    build:
      # Dockerfile の app のコピーのために必要なパス指定
      context: .
      # context のパスから見た Dockerfile の場所
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/opt/app
    ports:
      - "18080:8080"
      # for remote debug
      - "5005:5005"
